controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController
      
    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      

trajectory_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 1.0
    command_publish_rate: 1.0
    allow_partial_joints_goal: true
    constraints:
      goal_time: 10.0
      stopped_velocity_tolerance: 0.01
    
    
